### ISSUE TITLE
UNABLE TO INSTALL CHURCH CRM

### ISSUE THREAD

**Issue by Juliusyawson** [ChurchCRM/ChurchCRM.io#3]
Hi, Been trying to install Church CRM, i keep getting this error.
Kindly help me out.

![c__users_julius_pictures_maxthonsnap20160918030426](https://cloud.githubusercontent.com/assets/16658339/18612551/bad9ee98-7d4c-11e6-8b1c-c0f8be011716.png)

**Comment by DawoudIO** [comment]
Can you tell me about your setup as you as missing the get text lib

**Comment by Juliusyawson** [comment]
Tried running the setup at the initial stages and i get this fatal error.
[setup.docx](https://github.com/ChurchCRM/ChurchCRM.github.io/files/479062/setup.docx)
