### ISSUE TITLE
BCC all email issue

### ISSUE THREAD

**Issue by juhlman** [ChurchCRM/ChurchCRM.io#5]
Hi there, first time in the chat...I have a question regarding emailing from ChurchCRM. We decided not to use MailChimp because it looked like a pain - we just configured the CRM to reach out and use my email client (Outlook - latest version) and that was working fine for a while it seemed. Last time I went to members, dashboard, and clicked email BCC all, it put 80 out of the 94 email addresses in the BCC, and the last one was cut in half. Tried putting in a new member record with email and then doing it again. Same 80 listed, same last one cut in half. No new member email. So put everybody in the cart and tried emailing from there - same thing. Put everyone in the cart and exported to CSV, opened the excel file and there were 94 email addresses, all complete. So the data is there, and the data is getting to the cart, but all of it is not getting out of the cart (or out of the dashboard BCC all). Only most of it. I shouldn't have any limits in the BCC field as there are no limits on the latest version of Outlook. I'm stumped. Can you help? Hoping to not have to use MailChimp for a simple BCC all. Thanks!

**Comment by crossan007** [comment]
see https://github.com/ChurchCRM/CRM/issues/2600.  closing duplicate.
